# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.TimeField(blank=True, default='12:00'),
        ),
    ]
